joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# mycar_controller:
#   type: "diff_drive_controller/DiffDriveController"
#   left_wheel: 'joint_Lwheel'
#   right_wheel: 'joint_Rwheel'
#   pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
#   twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

#   base_frame_id: base_footprint

#   # Wheel separation and diameter. These are both optional.
#   # diff_drive_controller will attempt to read either one or both from the
#   # URDF if not specified as a parameter
#   wheel_separation : 0.059
#   wheel_radius : 0.02

#   # Wheel separation and radius multipliers
#   wheel_separation_multiplier: 1.0 # default: 1.0
#   wheel_radius_multiplier    : 1.0 # default: 1.0


# Position Controllers ---------------------------------------
Rwheel_controller:
  type: effort_controllers/JointVelocityController
  joint: joint_Rwheel
  pid: {p: 1.0, i: 0, d: 0}

Lwheel_controller:
  type: effort_controllers/JointVelocityController
  joint: joint_Lwheel
  pid: {p: 1.0, i: 0, d: 0}