joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50


# Joint Controllers ---------------------------------------
Rwheel_controller:
  type: effort_controllers/JointVelocityController
  joint: joint_Rwheel
  pid: {p: 1.0, i: 0, d: 0}

Lwheel_controller:
  type: effort_controllers/JointVelocityController
  joint: joint_Lwheel
  pid: {p: 1.0, i: 0, d: 0}
